const companyLabels = {
  companySelected: "Empresa con convenio",
  companyName: "Razón social",
  companyTypeIdent: "Tipo de documento",
  companyNumberIdent: "Número de documento",
  companyVerifDigit: "Dígito de verificación",
  companyDateIdent: "Fecha de expedición de identificación",
  companyNameCommercial: "Nombre comercial o alias",
  companyComplement: "Complemento",
  companyCity: "Ciudad",
  companyAddressRes: "Nomenclatura",
  companyCountry: "País de residencia fiscal",
  companyCountryIdent: "País emisor del documento",
  labelbutton: "Siguiente",
  placeholderCompanyName: "Nombre de la empresa",
  placeholderCompanySelected: "Selecciona de la lista",
  placeholderCompanyTypeIdent: "Selecciona de la lista",
  placeholdercompanyNameCommerc: "Nombre comercial",
  placeholderCompanyCountry: "Selecciona de la lista",
  placeholderCompanyNumberIdent: "Número de identificacíon",
  placeholderCompanyCountryIdent: "Selecciona de la lista",
  placeholderCompanyAddressRes: "Ej: Calle 10 #2a - 34",
  placeholderCompanyComplement: "Ej: Edificio rojo, oficina 202",
  placeholderCompanyCity: "Nombre de la ciudad",
  maxLengthCompanyName: 100,
  maxLengthcompanyNameCom: 30,
  maxLengthcompanyComplem: 30,
};

export { companyLabels };
